export const GET_BARTERS_REQUEST = 'GET_BARTERS_REQUEST';
export const GET_BARTERS_SUCCESS = 'GET_BARTERS_SUCCESS';
export const GET_BARTERS_FAILURE = 'GET_BARTERS_FAILURE';

export const POST_NEW_BARTER_REQUEST = 'POST_NEW_BARTER_REQUEST';
export const POST_NEW_BARTER_SUCCESS = 'POST_NEW_BARTER_SUCCESS';
export const POST_NEW_BARTER_FAILURE = 'POST_NEW_BARTER_FAILURE';

export const POST_EDITED_BARTER_REQUEST = 'POST_EDITED_BARTER_REQUEST';
export const POST_EDITED_BARTER_SUCCESS = 'POST_EDITED_BARTER_SUCCESS';
export const POST_EDITED_BARTER_FAILURE = 'POST_EDITED_BARTER_FAILURE';

export const DELETE_BARTER_REQUEST = 'DELETE_BARTER_REQUEST';
export const DELETE_BARTER_SUCCESS = 'DELETE_BARTER_SUCCESS';
export const DELETE_BARTER_FAILURE = 'DELETE_BARTER_FAILURE';

export const POST_NEW_COMMENT_REQUEST = 'POST_NEW_COMMENT_REQUEST';
export const POST_NEW_COMMENT_SUCCESS = 'POST_NEW_COMMENT_SUCCESS';
export const POST_NEW_COMMENT_FAILURE = 'POST_NEW_COMMENT_FAILURE';

export const DELELE_COMMENT_REQUEST = 'DELELE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';
